services:

  postgres:
    image: postgres:16
    container_name: hotel-booking-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: hotel_booking
      POSTGRES_USER: hotel_user
      POSTGRES_PASSWORD: hotel_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data


  pgadmin:
    image: dpage/pgadmin4
    container_name: hotel-booking-pgadmin
    restart: unless-stopped

    environment:
      PGADMIN_DEFAULT_EMAIL: admin@hotel.com
      PGADMIN_DEFAULT_PASSWORD: admin123

    ports:
      - "8080:80"

    volumes:
      - pgadmin_data:/var/lib/pgadmin

    depends_on:
      - postgres


volumes:
  postgres_data:
  pgadmin_data: